name: "CI/CD Workflow"
on:
  push:
    branches: [ master ]
#  release:
#    types: [created]
jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
#          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
#      - name: Setup nodejs 16
#        uses: actions/setup-node@v1
#        with:
#          node-version: '16.x'
#          registry-url: 'https://registry.npmjs.org'
##        # Rewrite package.json to have the package name scoped for publishing to the github repo.
##        - run: |
##            sed -i.orig "s/\(\"name\": \"\)\(procon-ip\"\)/\1@ylabonte\/\2/" package.json
#      - name: Install dependencies
#        run: npm ci
#      - name: Build
#        run: npm run build
#      - name: Run tests
#        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Setup nodejs 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
#            # Rewrite package.json to have the package name scoped for publishing to the github repo.
#            - run: |
#                sed -i.orig "s/\(\"name\": \"\)\(procon-ip\"\)/\1@ylabonte\/\2/" package.json
      - name: Install dependencies
        run: npm ci
      - name: Build for release
        run: npm run build:prod
      - name: Init git repo for publishing
        run: |
          cd ./dist/procon-ip-rc
          touch .nojekyll
          echo "procon-ip.labonte.cloud" > CNAME
          git config --global init.defaultBranch deployment
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git init
          git add --all
          git commit -am "Add changes"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "./dist/procon-ip-rc"
          repository: ylabonte/procon-ip-rc-live
          branch: deployment
          force: true
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
