name: CI/CD Workflow

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - master
      - develop

jobs:
  continuous-integration:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn run build
      - name: Run tests
        run: yarn run test:prod
      - name: Run linter
        run: yarn run lint
  continuous-deployment:
    name: Deploy app
    if: github.ref_name == 'master' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged))
    runs-on: ubuntu-latest
    needs: continuous-integration
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
      - name: Build for release
        run: yarn run build:prod
      - name: Init git repo for publishing
        run: |
          bash vfat-fixes
          cd ./dist/procon-ip-rc
          touch .nojekyll
          echo "procon-ip.labonte.cloud" > CNAME
          git config --global init.defaultBranch deployment
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git init
          git add --all
          git commit -am "Add changes"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: './dist/procon-ip-rc'
          repository: ylabonte/procon-ip-rc-live
          branch: deployment
          force: true
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
